# **Two Dimensional Arrays**
A 2D array (two-dimensional array) is a data structure used to represent a matrix or grid-like layout where data is organized in rows and columns.

It is essentially a list of lists in


In [1]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]

The above matrix has 3 rows and 3 columns - a 3x3 2D array.



# **Accessing Elements**
You can access an element at row i and column j using:

`element = matrix[i][j]`



In [2]:
print(matrix[1][2])

6


# **Traversing a 2D Array**
A use of nested loop lets us access the entries of a 2D array by indices.


In [3]:
for row in matrix:
    for element in row:
        print(element, end=' ')
    print()

1 2 3 
4 5 6 
7 8 9 


Or with indices:


In [4]:
for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        print(matrix[i][j], end=' ')
    print()

1 2 3 
4 5 6 
7 8 9 


# **Using NumPy**
For numerical work, the numpy library is more powerful:

In [5]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a.shape)
print(a[0, 1])

(2, 2)
2


NumPy supports operations like addition, multiplication, transpose, etc., directly on arrays.

### **Applications**
* Image processing (grayscale image as a 2D array)
* Game grids (like Sudoku, Minesweeper)
* Mathematical computations (matrix algebra)
* Simulations (heat maps, physics grids)
* Data science (tables, correlation matrices)


# **Arithmetic Operations**
In NumPy, you can perform element-wise arithmetic operations easily on 2D arrays (matrices).


In [6]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [7]:
# Addition
C = A + B
print(C)

[[ 6  8]
 [10 12]]


In [8]:
# Subtraction
C = A - B
print(C)

[[-4 -4]
 [-4 -4]]


In [9]:
# Multiplication (Element-wise)
C = A * B
print(C)


[[ 5 12]
 [21 32]]


In [10]:
# Division (Element-wise)
C = A / B
print(C)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [11]:
# Matrix Multiplication
# More on this later!
# Use @ or np.dot() for actual matrix multiplication:
C = A @ B
print(C)


[[19 22]
 [43 50]]


# **Slicing 2D Arrays**
Slicing allows you to extract sub-arrays or specific rows/columns.


In [12]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

Syntax:

`arr[start_row:end_row, start_col:end_col]`

In [13]:
# Extract first row
arr[0, :]  # Output: [10 20 30]

array([10, 20, 30])

In [14]:
# Extract second column:
arr[:, 1]  # Output: [20 50 80]

array([20, 50, 80])

In [15]:
# Extract top-left 2x2 block:
arr[0:2, 0:2]

array([[10, 20],
       [40, 50]])

`arr[start:stop:step, start:stop:step]`

In [16]:
# Reverse row order:
arr[::-1, :]

array([[70, 80, 90],
       [40, 50, 60],
       [10, 20, 30]])

In [17]:
# Reverse column order:
arr[:, ::-1]

array([[30, 20, 10],
       [60, 50, 40],
       [90, 80, 70]])

# **Broadcasting:**
We can apply scalar operations directly to all elements.

In [18]:
arr * 2

array([[ 20,  40,  60],
       [ 80, 100, 120],
       [140, 160, 180]])

It is possible to combine slicing with arithmetic operations and broadcasting.

In [19]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [20]:
arr[0:2, 1:3]

array([[20, 30],
       [50, 60]])

In [21]:
arr[0:2, 1:3] + 5

array([[25, 35],
       [55, 65]])

# **Problem: Transpose of a Matrix**
Write a Python program that takes a 2D array (matrix) as input and returns its transpose.

### **Description:**<br>
The transpose of a matrix is obtained by flipping it over its diagonal. That is, the rows become columns and the columns become rows.

### **Exercise**
Design a function `transpose_matrix(matrix)` that takes a 2D list or a NumPy array and returns a new matrix that is the transpose of the input.

**Example:**

Input:

```
matrix = [[1, 2],
          [3, 4],
          [5, 6]]
```

Output:
```
[[1, 3, 5],
 [2, 4, 6]]
```


In [22]:
# Transpose of a matrix
def transpose_matrix(A):
    A = np.array(A, dtype=int)
    r = np.shape(A)[0]
    c = np.shape(A)[1]

    B = np.zeros((c,r), dtype =int)

    for i in range(r):
        for j in range(c):
            B[j,i]=A[i,j]
    return B

In [23]:
matrix = [[1, 2],
          [3, 4],
          [5, 6]]
print(np.shape(matrix))
print(transpose_matrix(matrix))
print(np.shape(transpose_matrix(matrix)))

(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [24]:
# Numpy has its own transpose function
print(np.transpose(matrix))

[[1 3 5]
 [2 4 6]]


# **Problem: Row and Column Sums of a Matrix**
Write a Python function that takes a 2D NumPy array (matrix) as input and returns:

* A 1D array of row sums (sum of each row),
* A 1D array of column sums (sum of each column).

Input:
```
[[3, 5, 1],
 [2, 8, 6],
 [4, 7, 9]]
```

Output:
```
row_sums = [9, 16, 20]
column_sums = [9, 20, 16]
```

In [25]:
# Row and Column sum of a matrix
def row_column_sums(A):
    A = np.array(A,dtype = int)
    r = np.shape(A)[0]
    c = np.shape(A)[1]

    row_sums = np.zeros(r, dtype=int)
    column_sums = np.zeros(c, dtype = int)

    for i in range(r):
        for j in range(c):
            row_sums[i] += A[i,j]
            column_sums[j] += A[i,j]

    return row_sums, column_sums

In [26]:
A = [
    [3, 5, 1],
     [2, 8, 6],
      [4, 7, 9]
]

rs,cs = row_column_sums(A)
print('Row sums = ',rs)
print('Column sums = ', cs)

Row sums =  [ 9 16 20]
Column sums =  [ 9 20 16]


# **Problem: Matrix Multiplication**
Write a Python program to perform matrix multiplication of two given 2D arrays.

### **Description:**
Matrix multiplication is a fundamental operation in linear algebra where two matrices are multiplied to produce a third matrix. Given two matrices A and B, the product $C = A \times B$ is defined only if the number of columns in $A$ is equal to the number of rows in $B$.

### **How It Works**
Let $C_{ij}$ be the entry in the matrix $C$.

To compute each entry $C_{ij}$:

* Take the $i$-th row of matrix $A$
* Take the $j$-th column of matrix $B$
* Compute the dot product of these two vectors (Sum of element-wise multiplication of the entries)

Mathematically:

$$
C_{ij}=
\sum\limits_{k=1}^n A_{ik} B_{kj}
$$

### **Exercise**
* Write a function `matrix_multiply(A, B)` that multiplies two 2D lists or NumPy arrays.
* Ensure the function checks for dimension compatibility before performing multiplication.
* Return the resulting product matrix.

### **Example:**

Input:
```
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Output:
```
[[19, 22],
 [43, 50]]
```

In [27]:
def matrix_multiply(A,B):
    A = np.array(A, dtype = int)
    B = np.array(B, dtype=int)

    row_A = np.shape(A)[0]
    col_A = np.shape(A)[1]

    row_B = np.shape(B)[0]
    col_B = np.shape(B)[1]

    if col_A != row_B:
        print("Invalid matrix product")
        return None

    C = np.zeros((row_A, col_B), dtype = int)

    for i in range(row_A):
        for j in range(col_B):
            for k in range(col_A):
                C[i,j] += A[i,k]*B[k,j]

    return C

In [28]:
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]

print(matrix_multiply(A,B))

[[19 22]
 [43 50]]


In [29]:
# As mentioned before this can be done using numpy.dot()
print(np.dot(A,B))

[[19 22]
 [43 50]]


# **Problem: Spiral Traversal of a Matrix**

Write a Python function that takes a 2D array (matrix) as input and returns a list of its elements in spiral order, starting from the top-left corner and moving clockwise.

### **Example**

Input:
```
[
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]
]
```
Output:
```
[1, 2, 3, 6, 9, 8, 7, 4, 5]
```

In [32]:
# We will solve this problem using recursion and slicing
def spiral_matrix(A):
    A = np.array(A, dtype = int)

    r = np.shape(A)[0]
    c = np.shape(A)[1]

    if r == 1:
        return np.array(A, dtype = int)
    spir = np.array([], dtype = int)
    spir = np.concatenate((spir, A[0,:]))
    spir = np.concatenate((spir, A[1:,-1]))
    spir = np.concatenate((spir, A[-1,-2::-1]))
    spir = np.concatenate((spir, A[-2:0:-1,0]))

    return np.append(spir,spiral_matrix(A[1:-1,1:-1]))

In [33]:
A = np.array( [
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]

])

print(spiral_matrix(A))

[ 1  2  3  4  8 12 11 10  9  5  6  7]


# **Problem: Generate a Magic Square**

A magic square is an $n \times n$ grid filled with distinct positive integers such that the numbers in each row, each column, and both main diagonals all add up to the same total.

Write a Python program that:

* Accepts an **odd integer** $n (n ≥ 3)$ from the user.
* Generates a magic square of order $n$.
* Prints the resulting square in a readable format.
* Prints the common sum of rows, columns, and diagonals.

### **Example (n = 3):**
```
 8 1 6
 3 5 7
 4 9 2

All rows, columns, and diagonals add up to 15.
```

### **Algorithm:**
Use the Siamese method for constructing magic squares of odd order:
* Place the number 1 in the middle of the top row.
* Move up and right for the next number.
* If the cell is occupied move down one row instead.
* If the cell is out of bound, you need to wrap around.


In [35]:
def magic_sq(n):
    mag = np.zeros((n,n), dtype = int)

    row = 0
    col = (n-1)//2
    for i in range(1,n*n+1):
        if mag[row,col] == 0:
            mag[row,col] = i
        else:
            row += 2
            row %= n
            col -= 1
            col %= n
            mag[row,col] = i
        row -= 1
        row %= n
        col += 1
        col %= n

    return mag

In [36]:
print(magic_sq(5))

[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]


Here are Python functions to compute the row sum, column sum, and diagonal sums of a 2D NumPy array.

In [37]:
# Row Sum Function:
def row_sums(matrix):
    return np.sum(matrix, axis=1)

# Column Sum Function:
def column_sums(matrix):
    return np.sum(matrix, axis=0)

# Diagonal Sums:
def main_diagonal_sum(matrix):
    return np.trace(matrix)            # Trace is the diagonal sum

def secondary_diagonal_sum(matrix):
    return np.trace(np.fliplr(matrix)) # Flips every row

In [38]:
mag = magic_sq(5)

print("Magic square: ")
print()
print(mag)

print("\nRow sums:", row_sums(mag))
print("Column sums:", column_sums(mag))
print("Main diagonal sum:", main_diagonal_sum(mag))
print("Secondary diagonal sum:", secondary_diagonal_sum(mag))


Magic square: 

[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]

Row sums: [65 65 65 65 65]
Column sums: [65 65 65 65 65]
Main diagonal sum: 65
Secondary diagonal sum: 65
